// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qwzomtguhplynhciriuf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF3em9tdGd1aHBseW5oY2lyaXVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMjM0NTQsImV4cCI6MjA2Mzg5OTQ1NH0.BBXEVybRI7-DzVWhjsSwyaZjgisLqKAdZQsRFqlpGsc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);